#!/bin/sh
# all-emails: print sanitized list of all emails

SRC_DIR=$(cd "$(dirname "$0")/.."; pwd)

ENTRIES_FILE=$SRC_DIR/entries/all.txt
[ -r $ENTRIES_FILE ] ||
  exit 1

cat $ENTRIES_FILE |
grep -v '^#' | # ignore comments
grep -v '^\s*$' | # ignore blank lines
sort |
uniq
