#!/bin/sh
# opt-out-emails: print sanitized list of opt-out emails

SRC_DIR=$(cd "$(dirname "$0")/.."; pwd)

ENTRIES_FILE=$SRC_DIR/entries/opt-out.txt
[ -r $ENTRIES_FILE ] ||
  exit 1

cat $ENTRIES_FILE |
grep -v '^#' | # ignore comments
grep -v '^\s*$' | # ignore blank lines
sort |
uniq
